development:
  adapter: mysql2
  encoding: utf8
  database: ff
  pool: 5
  username: dev 
  password: test
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  database: ff
  pool: 5
  username: dev 
  password: test
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  database: ff
  pool: 5
  username: dev 
  password: test
  socket: /var/run/mysqld/mysqld.sock
